settings:
  name: "NetApp public and hybrid cloud solutions"
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: true
  pdf: 
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-cloud.zip

product-family:
  name: NetApp solutions
  repo: netapp-solutions-family

sidebar:
  entries:
    - title: "Public and hybrid cloud solutions"
      url: /index.html
    - section: ehc
    - section: vmw-sc
    - section: rhhc

 #
    - title: "Videos"
      url: /videos.html
    - title: "Blogs"
      url: /blogs.html
    - title: "Change Log"
      url: /whats-new.html
    - title: "Legal notices"
      url: /legal-notices.html

