---
sidebar: sidebar
permalink: google/gcp-gcnv-firewall.html
keywords: tcp, nfs, smb share, kerberos, active directory, dns
summary: Google Cloud NetApp Volumes exposes multiple TCP ports to serve NFS and SMB shares.
---

= Firewall
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-09 14:20:40.965446
//

[.lead]
Google Cloud NetApp Volumes exposes multiple TCP ports to serve NFS and SMB shares:

* https://docs.cloud.google.com/netapp/volumes/docs/connect-clients/connect-nfs-clients#firewall_rules_for_nfs_volumes_access[Ports required for NFS access^]
* https://docs.cloud.google.com/netapp/volumes/docs/connect-clients/connect-smb-clients#firewall_rules_for_smb_volumes_access[Ports required for SMB access^]

Additionally, SMB, NFS with LDAP including Kerberos, and dual-protocol configurations require access to a Windows Active Directory domain. Active Directory connections must be https://docs.cloud.google.com/netapp/volumes/docs/configure-and-use/active-directory/create-ad-policy[configured^] on a per-region basis. Active Directory Domain controllers (DC) are identified by using https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04[DNS-based DC discovery^] using the specified DNS servers. Any of the DCs returned are used. The list of eligible DCs can be limited by specifying an Active Directory site.

Google Cloud NetApp Volumes reaches out with IP addresses from the CIDR range allocated with the `gcloud compute address` command while https://docs.cloud.google.com/netapp/volumes/docs/plan-and-prepare/networking#configure_private_services_access[on-boarding the Google Cloud NetApp Volumes^]. You can use this CIDR as source addresses to configure inbound firewalls to your Active Directory domain controllers.

Active Directory Domain Controllers must https://docs.cloud.google.com/netapp/volumes/docs/plan-and-prepare/security-considerations[expose ports to the Google Cloud NetApp Volumes CIDRs as mentioned here^].


// NetApp Solutions restructuring (jul 2025) - renamed from ehc/ncvs-gc-firewall.adoc
