---
sidebar: sidebar
permalink: videos/hmc-aws-videos.html
summary: Videos and demos showcasing AWS hybrid multicloud solutions with NetApp
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos
---
= Watch videos on hybrid multicloud solutions for Amazon Web Services with NetApp 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Explore NetApp's comprehensive video library featuring hybrid multicloud solutions for AWS with NetApp. Watch videos on guest connected storage, TCO savings, supplemental datastores, and migration workflows for VMware Cloud on AWS and Amazon FSx for ONTAP, including Windows and Linux scenarios.


== Guest connected storage

video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto, title="Windows Guest Connected Storage with FSx ONTAP using iSCSI", width=360]
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto, title="Linux Guest Connected Storage with FSx ONTAP using NFS", width=360]

== TCO and supplemental datastores

video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto, title="VMware Cloud on AWS TCO savings with Amazon FSx ONTAP", width=360]
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto, title="VMware Cloud on AWS supplemental datastore w/ Amazon FSx ONTAP", width=360]

== Migration workflows (HCX)

video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto, title="VMware HCX Deployment and Configuration Setup for VMC", width=360]
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto, title="vMotion Migration Demonstration with VMware HCX for VMC and FSx ONTAP", width=360]
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto, title="Cold Migration Demonstration with VMware HCX for VMC and FSx ONTAP", width=360]

